#!/usr/bin/env python3
"""Generate .vscode/settings.json entries to hide redirect stub pages in the file tree."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SETTINGS_FILE = ROOT / ".vscode" / "settings.json"
REDIRECT_MARKER = "<!-- ek-redirect-stub -->"
KEEP_ROOT_PAGES = {"index.html", "progress.html", "feedback.html"}


def find_redirect_stubs() -> list[str]:
    stubs: list[str] = []
    for path in ROOT.rglob("*.html"):
        rel = path.relative_to(ROOT)
        if rel.parts and rel.parts[0] in {".git", ".github", "node_modules"}:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if REDIRECT_MARKER not in text:
            continue
        if rel.parent == Path(".") and rel.name in KEEP_ROOT_PAGES:
            continue
        stubs.append(rel.as_posix())
    return sorted(set(stubs))


def build_settings(stubs: list[str]) -> dict:
    exclude = {path: True for path in stubs}
    return {
        "files.exclude": exclude,
        "search.exclude": exclude,
    }


def write_settings(settings: dict) -> None:
    SETTINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
    header = "// Generated by scripts/build-vscode-excludes.py — do not edit by hand\n"
    SETTINGS_FILE.write_text(header + json.dumps(settings, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    stubs = find_redirect_stubs()
    write_settings(build_settings(stubs))
    print(f"Wrote {SETTINGS_FILE.relative_to(ROOT)} ({len(stubs)} redirect stub(s) hidden)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
