#!/usr/bin/env python3
"""Build js/topic-catalog.json from Mathematics, Physics, and Quantum catalog pages."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

CATALOGS = [
    {
        "id": "math",
        "label": "Mathematics",
        "catalog_href": "pure_math_subjects.html",
        "file": "pure_math_subjects.html",
    },
    {
        "id": "physics",
        "label": "Physics",
        "catalog_href": "physics_subjects.html",
        "file": "physics_subjects.html",
    },
    {
        "id": "quantum",
        "label": "Quantum",
        "catalog_href": "quantum_subjects.html",
        "file": "quantum_subjects.html",
    },
]

LINK_RE = re.compile(
    r'<li>\s*<a\s+href="([^"]+\.html)">([^<]+)</a>\s*</li>',
    re.IGNORECASE,
)
SECTION_RE = re.compile(r"<section>(.*?)</section>", re.DOTALL | re.IGNORECASE)
H2_RE = re.compile(r"<h2>(.*?)</h2>", re.DOTALL | re.IGNORECASE)


def parse_catalog(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    sections = []
    for block in SECTION_RE.findall(text):
        h2 = H2_RE.search(block)
        if not h2:
            continue
        title = re.sub(r"<[^>]+>", "", h2.group(1)).strip()
        topics = []
        for href, link_title in LINK_RE.findall(block):
            href = href.replace("\\", "/").lstrip("./")
            topics.append(
                {
                    "id": href,
                    "title": link_title.strip(),
                    "href": href,
                }
            )
        if topics:
            sections.append({"title": title, "topics": topics})
    return sections


def main():
    catalogs = []
    for meta in CATALOGS:
        sections = parse_catalog(ROOT / meta["file"])
        catalogs.append(
            {
                "id": meta["id"],
                "label": meta["label"],
                "catalog_href": meta["catalog_href"],
                "sections": sections,
            }
        )
    payload = {"catalogs": catalogs}
    json_out = ROOT / "js" / "topic-catalog.json"
    js_out = ROOT / "js" / "topic-catalog.js"
    json_text = json.dumps(payload, indent=2)
    json_out.write_text(json_text, encoding="utf-8")
    js_out.write_text(
        "/* Auto-generated by scripts/build-topic-catalog.py — do not edit */\n"
        "window.EK_TOPIC_CATALOG = " + json.dumps(payload) + ";\n",
        encoding="utf-8",
    )
    total = sum(len(s["topics"]) for c in catalogs for s in c["sections"])
    print(f"Wrote {total} topics across {len(catalogs)} catalogs to {json_out} and {js_out}")


if __name__ == "__main__":
    main()
