#!/usr/bin/env python3
"""Build assets/js/topic-catalog.js from Mathematics, Physics, and Quantum catalog pages."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

CATALOGS = [
    {
        "id": "math",
        "label": "Mathematics",
        "catalog_href": "learn/mathematics/index.html",
        "file": "learn/mathematics/index.html",
    },
    {
        "id": "physics",
        "label": "Physics",
        "catalog_href": "learn/physics/index.html",
        "file": "learn/physics/index.html",
    },
    {
        "id": "quantum",
        "label": "Quantum",
        "catalog_href": "learn/quantum/index.html",
        "file": "learn/quantum/index.html",
    },
]

LINK_RE = re.compile(
    r'<li>\s*<a\s+href="([^"]+\.html)">([^<]+)</a>\s*</li>',
    re.IGNORECASE,
)
SECTION_RE = re.compile(r"<section>(.*?)</section>", re.DOTALL | re.IGNORECASE)
H2_RE = re.compile(r"<h2>(.*?)</h2>", re.DOTALL | re.IGNORECASE)


def normalize_href(href: str, catalog_file: str) -> str:
    href = href.replace("\\", "/")
    if href.startswith("./"):
        href = href[2:]
    if href.startswith(("http://", "https://")):
        return href
    catalog_dir = (ROOT / catalog_file).parent
    return (catalog_dir / href).resolve().relative_to(ROOT).as_posix()


def parse_catalog(path: Path, catalog_file: str) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    sections = []
    for block in SECTION_RE.findall(text):
        h2 = H2_RE.search(block)
        if not h2:
            continue
        title = re.sub(r"<[^>]+>", "", h2.group(1)).strip()
        topics = []
        for href, link_title in LINK_RE.findall(block):
            full_href = normalize_href(href, catalog_file)
            topics.append(
                {
                    "id": full_href,
                    "title": link_title.strip(),
                    "href": full_href,
                }
            )
        if topics:
            sections.append({"title": title, "topics": topics})
    return sections


def main():
    catalogs = []
    for meta in CATALOGS:
        sections = parse_catalog(ROOT / meta["file"], meta["file"])
        catalogs.append(
            {
                "id": meta["id"],
                "label": meta["label"],
                "catalog_href": meta["catalog_href"],
                "sections": sections,
            }
        )
    payload = {"catalogs": catalogs}
    out_dir = ROOT / "assets" / "js"
    out_dir.mkdir(parents=True, exist_ok=True)
    json_out = out_dir / "topic-catalog.json"
    js_out = out_dir / "topic-catalog.js"
    json_text = json.dumps(payload, indent=2)
    json_out.write_text(json_text, encoding="utf-8")
    js_out.write_text(
        "/* Auto-generated by scripts/build-topic-catalog.py — do not edit */\n"
        "window.EK_TOPIC_CATALOG = " + json.dumps(payload) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(catalogs)} catalogs to {js_out}")


if __name__ == "__main__":
    main()
